apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quillpen.fullname" . }}
  labels:
    {{- include "quillpen.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "quillpen.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "quillpen.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "quillpen.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 443
          readinessProbe:
            httpGet:
              path: /health
              port: 443
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          {{- if  .Values.tls.enabled }} 
          volumeMounts:
            - name: cert-volume
              mountPath: /etc/tls
              readOnly: true
          {{- end }}
      
      {{- if  .Values.tls.enabled }}
      volumes:
        - name: cert-volume
          secret:
            secretName: {{ .Values.tls.secretName }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
