apiVersion: v1
kind: Service
metadata:
  name: {{ include "quillpen.fullname" . }}
  labels:
    {{- include "quillpen.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      port: 443
      protocol: TCP
      name: http
  selector:
    {{- include "quillpen.selectorLabels" . | nindent 4 }}
