apiVersion: v1
kind: Service
metadata:
  name: {{ include "quillpen.fullname" . }}   
spec:
  type: {{ .Values.service.type }}
  ports:
    - targetPort: 80
      port: 80
      protocol: TCP
        
  selector:
    {{- include "quillpen.selectorLabels" . | nindent 4 }}
