apiVersion: v1
kind: Service
metadata:
  name: {{ include "quillpen.fullname" . }}
  labels:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:783686645338:certificate/3003c275-73ce-429b-9f0c-0bb021e95d8c"
   
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 
        targetPort: 80
        port: 443
        protocol: TCP
        name: https
  selector:
    {{- include "quillpen.selectorLabels" . | nindent 4 }}
