name: CI Pipeline for Golang

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  bazel-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Bazelisk
        run: |
          go install github.com/bazelbuild/bazelisk@latest
      - name: Build with Bazel
        run: |
          bazelisk build //:quillpen

  bazel-test:
    needs: bazel-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Bazel Tests
        run: |
          bazelisk test //:quillpen
