name: "CI"
on: ["push", "pull_request"]

jobs:
  ci:
    name: "Run CI Lint" 
    runs-on: "ubuntu-latest" 
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - uses: actions/setup-go@v5
      with:
       go-version: '>=1.23.0'
    - run: "go test ./..."
    - run: "go vet ./..."
    - uses: dominikh/staticcheck-action@v1.13.1
      with:
        version: "latest"
        install-go: false