name: "CI"
on: ["push", "pull_request"]

jobs:
  ci:
    name: "Run CI Lint" 
    strategy:
      fail-fast: false
      matrix:
        os:  ["windows-latest", "ubuntu-latest", "macOS-latest"]
        go:  ["1.23.x"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - uses: actions/setup-go@v5
      with:
       go-version: '>=1.23.0'
    - run: "go test ./..."
    - run: "go vet ./..."
    - uses: dominikh/staticcheck-action@v1.13.1
      with:
        version: "latest"
        install-go: false